site_name: Sonari
site_url: https://mbsantiago.github.io/sonari/
nav:
  - Home: README.md
  - User Guide:
      - user_guide/index.md
      - Installation: user_guide/installation.md
      - Datasets: user_guide/datasets.md
      - Annotation Projects: user_guide/annotation_projects.md
      - Evaluation: user_guide/evaluation.md
      - Data Exploration: user_guide/exploration.md
      - FAQ: user_guide/faq.md
  - Developer Guide:
      - developer_guide/index.md
      - Quickstart: developer_guide/quickstart.md
      - Architecture: developer_guide/architecture.md
      - Database Layer: developer_guide/database.md
      - Python API: developer_guide/api.md
      - HTTP REST API: developer_guide/rest_api.md
      - Front End: developer_guide/front_end.md
      - Plugins: developer_guide/plugins.md
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - Reference:
      - Models: reference/models.md
      - Python API: reference/api.md
      - Schemas: reference/schemas.md
  - About the Project:
      - Authors: AUTHORS.md
      - Sponsors: sponsors.md
theme:
  name: material
  logo: assets/logo.svg
  font:
    text: Mulish
  favicon: assets/favicon.svg
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          import:
            - https://docs.python.org/3.11/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://mbsantiago.github.io/soundevent/objects.inv
            - https://docs.sqlalchemy.org/en/20/objects.inv
            - https://fastapi.tiangolo.com/objects.inv
          options:
            show_source: false
            show_root_toc_entry: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_category_heading: true
            show_symbol_type_heading: true
            show_if_no_docstring: true
            docstring_style: "numpy"
            docstring_section_style: "table"
            summary: true
            signature_crossrefs: true
            show_signature_annotations: false
            filters:
              - "!^_"
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
watch:
  - docs
  - src
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - admonition
  - tables
  - md_in_html
  - toc:
      toc_depth: 4
      permalink: true
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
extra_javascript:
  - javascripts/jquery-3.3.1.min.js
  - javascripts/jquery.json-viewer.js
  - javascripts/json-viewer.js
extra_css:
  - stylesheets/jquery.json-viewer.css
  - css/mkdocstrings.css
