name: Bundle App
on:
  release:
    types: [published]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    needs: [build-user-guide, build-frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@v4
        with:
          name: frontend
          path: back/src/sonari/statics/
      - uses: actions/download-artifact@v4
        with:
          name: user_guide
          path: back/src/sonari/user_guide/
      - run: bash scripts/bundle_linux.sh
      - run: |
          mkdir dist/
          mv back/dist/sonari.zip "dist/sonari-ubuntu-${{ github.ref_name }}.zip"
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/sonari-ubuntu-${{ github.ref_name }}.zip"
